name: cookbook-typescript
resources:
  repositories:
    - repository: self

trigger:
  - main
  - development


variables:
  - template: configuration\collective.yml

stages:
  - stage: build_CI
    displayName: Build    
    jobs:
      - job:
        pool:
          vmImage: $(vmImage)
        steps:
        - powershell: |
            write-host "building"

# -----------------------------------------------------------------------------------------
# -                                  Deploy Development                                   -
# -----------------------------------------------------------------------------------------
  - stage: deploy_itest
    displayName: Deploy I-Test
    dependsOn: build_CI
    condition: and(startsWith(variables['Build.SourceBranchName'], 'development'), succeeded('build_CI'))
    
    variables:
    - template: configuration\test.yml

    jobs:
    - deployment:
      pool:
        vmImage: $(vmImage)
      environment: itest-env
      strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                  write-host "deploying test"

              - template: templates\deployment.yml
                parameters:
                  location: $(location)
                  outputFile: $(pathToConfOutput)
                  pathToZip: $(pathToZip)
                  resourceGroup: $(resourceGroup)
                  subscriptionId: $(subscriptionId)
                  pathToArmTemplate: $(pathToArmTemplate)
                  azureSubscription: CookBookAzureConnection
                  overrideParameters: ''
                  pathToArmParameters: $(pathToArmParameters)
                  pathToGenerateConfigJs: $(pathToGenerateConfigurationJs)
                  pathToUploadScriptPs1: $(pathToUploadScript)