name: cookbook-typescript
resources:
  repositories:
    - repository: self

trigger:
  - main
  - development


variables:
  - template: configuration\collective.yml

stages:
 

  - stage: build_CI
    displayName: Build    
    condition: in(dependencies.bump_and_changelog_publish_dotnet.result, 'Skipped')
    jobs:
      - job:
        pool:
          vmImage: $(vmImage)
        steps:
        - powershell: |
            write-host "building"

# -----------------------------------------------------------------------------------------
# -                                  Deploy Development                                   -
# -----------------------------------------------------------------------------------------
  - stage: deploy_itest
    displayName: Deploy I-Test
    dependsOn: build_CI
    condition: and(startsWith(variables['Build.SourceBranchName'], 'development'), succeeded('build_CI'))
    
    variables:
    - template: configuration\test.yml

    jobs:
    - deployment:
      pool:
        vmImage: $(vmImage)
      environment: itest-env
      strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                  write-host "deploying"