
parameters:
  buildScriptPath: ''
  sourceFolder: ''
  targetFolder: ''

steps:
# - checkout: self
# - checkout: DevOpsArena

- powershell: |
    write-host "buildScriptPath: ${{ parameters.buildScriptPath }}"
    write-host "sourceFolder: ${{ parameters.sourceFolder }} "
    write-host "targetFolder: ${{ parameters.targetFolder }} "
- powershell: |
    dir

- script: ${{ parameters.buildScriptPath }}
  displayName: 'Build Script (Fake)'

- task: CopyFiles@2
  displayName: 'Copy Files from source to target'
  inputs:
    sourceFolder: ${{ parameters.sourceFolder }}
    contents: '**'
    targetFolder: ${{ parameters.targetFolder }}

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: ${{ parameters.targetFolder }}
    artifactName: drop


